# ⚠️ This configuration is intended for development environment.
# If you'd like to override anything, create a Revolt.override.toml

[database]
# MongoDB connection URL
# Defaults to the container name specified in self-hosted
mongodb = "mongodb://127.0.0.1:14017"
# Redis connection URL
# Defaults to the container name specified in self-hosted
redis = "redis://127.0.0.1:14079/"

[hosts]
# Web locations of various services
# Defaults assume all services are reverse-proxied
# See https://github.com/revoltchat/self-hosted/blob/master/Caddyfile
#
# Remember to change these to https/wss where appropriate in production!
app = "http://streamclashstaff.com:14701"
api = "http://streamclashstaff.com:14702"
events = "ws://streamclashstaff.com:14703"
autumn = "http://streamclashstaff.com:14704"
january = "http://streamclashstaff.com:14705"
voso_legacy = ""
voso_legacy_ws = ""

[api]

[api.smtp]
# Email server configuration for verification
# Defaults to no email verification (host field is empty)
host = "streamclashstaff.com"
username = "smtp"
password = "smtp"
from_address = "development@revolt.chat"
reply_to = "support@revolt.chat"
port = 14025
use_tls = false

[files.s3]
# S3 protocol endpoint
endpoint = "http://127.0.0.1:14009"
# S3 region name
region = "minio"
# S3 protocol key ID
access_key_id = "minioautumn"
# S3 protocol access key
secret_access_key = "minioautumn"
# Bucket to upload to by default
default_bucket = "revolt-uploads"
